ZeegaEditorBundle_new:
    pattern: /project/new
    defaults: { _controller:  ZeegaEditorBundle:Editor:newProject }

ZeegaEditorBundle_editor:
    pattern: /editor/{id}
    defaults: { _controller:  ZeegaEditorBundle:Editor:editor }

ZeegaEditorBundle_editor_old:
    pattern: /site/home/project/{id}
    defaults: { _controller:  ZeegaEditorBundle:Editor:editor }