ZeegaEditorBundle_new:
    pattern: /project/new
    defaults: { _controller:  ZeegaEditorBundle:Editor:newProject }

ZeegaEditorBundle_editor:
    pattern: /editor/{id}
    defaults: { _controller:  ZeegaEditorBundle:Editor:editor }

ZeegaEditorBundle_neweditor:
    pattern: /neweditor/{id}
    defaults: { _controller:  ZeegaEditorBundle:Editor:newEditor }