parameters:
#    zeega_editor.example.class: Zeega\EditorBundle\Example

services:
#    zeega_editor.example:
#        class: %zeega_editor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    zeega_user.registration.form.type:
        class: Zeega\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: zeega_user_registration }