security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        search:
            pattern:  ^/api/search
            anonymous: ~
        tags:    
            pattern: ^/api/tags
            anonymous: ~
        items:  
            pattern: ^/api/items
            anonymous: ~        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        node:
            pattern:  ^/node/
            anonymous: ~
        init:
            pattern:  ^/init
            anonymous: ~
        nodes:
            pattern:  ^/nodes
            anonymous: ~
        layers:
            pattern:  ^/layers/
            anonymous: ~
        route:
            pattern:  ^/route/
            anonymous: ~
        search:
            pattern: ^/api/search
            anonymous: ~
        tags:
            pattern: ^/api/tags
            anonymous: ~
        routes:
            pattern:  ^/routes/
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                #csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /login
            anonymous: true
            
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
