
_security_login:
    pattern:  /login
    defaults: { _controller:  ZeegaUserBundle:Security:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

admin_home:
    pattern:  /admin/
    defaults: { _controller:  ZeegaUserBundle:Admin:index }

   