# src/Zeega/UserBundle/Resources/config/doctrine/User.orm.yml
Zeega\UserBundle\Entity\User:
   type: entity
   id:
    id:
     type: integer
     generator: { strategy: AUTO }
   fields:
    username:
     type: string
     length: 255
     unique: true
    display_name:
     type: string
     length: 255
     nullable: true
    bio:
     type: text
     nullable: true
    thumb_url:
     type: string
     length: 255
     nullable: true
    password:
     type: string
     length: 255
    email:
     type: string
     length: 255
     unique: true
    salt:
     type: string
     length: 255
    created_at:
     type: datetime
     nullable: true
    user_roles:
     type: text
     nullable: false
