# src/Zeega/UserBundle/Resources/config/doctrine/User.orm.yml
Zeega\UserBundle\Entity\User:
   tableName: zeega_user
   type: entity
   id:
    id:
     type: integer
     generator: { strategy: AUTO }
   fields:
    display_name:
     type: string
     length: 255
     nullable: true
    bio:
     type: text
     nullable: true
    thumb_url:
     type: string
     length: 255
     nullable: true
    created_at:
     type: datetime
     nullable: true
