# src/Zeega/IngestBundle/Resources/config/doctrine/ItemTags.orm.yml
Zeega\IngestBundle\Entity\ItemTags:
    type: entity
    repositoryClass: Zeega\IngestBundle\Repository\ItemTagsRepository
    manyToOne:
        user:
            targetEntity: Zeega\UserBundle\Entity\User
        item:
            targetEntity: Item
            inversedBy: tags
            joinColumn:
                name: item_id
                referencedColumnName: id
        tag:
            targetEntity: Tag
            inversedBy: items
            joinColumn:
                name: tag_id
                referencedColumnName: id
    id:
        item:
            associationKey: true
        tag:
            associationKey: true
    fields:
        tag_date_created:
            type: date
            nullable: false