# src/Zeega/IngestBundle/Resources/config/doctrine/Item.orm.yml
Zeega\IngestBundle\Entity\Item:
    type: entity
    repositoryClass: Zeega\IngestBundle\Repository\ItemRepository
    manyToMany:
        child_items: 
            targetEntity: Item
            inversedBy: parent_items
            joinTable:
                name: Collection
                joinColumns:
                    id:
                        referencedColumnName: id
                inverseJoinColumns:
                    child_item_id:
                        referencedColumnName: id
        parent_items:
            targetEntity: Item
            mappedBy: child_items
    oneToOne:
        user:
            targetEntity: Zeega\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
        
    oneToMany:
        tags:
            targetEntity: ItemTags
            mappedBy: item
            joinColumn:
                name: id
                referencedColumnName: item_id            
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 1000
            nullable: true
        user_id:
            type: integer
            nullable: false
        description:
            type: string
            length: 500
            nullable: true
        uri:
            type: string
            length: 200
        attribution_uri:
            type: string
            length: 200
        date_created:
            type: date
            nullable: false
        type:
            type: string
            length: 20
            nullable: false
        source:
            type: string
            length: 20
            nullable: false        
        thumbnail_url:
            type: string
            length: 100
            nullable: true
        child_items_count:
            type: integer
            nullable: false
            default: 0
        media_geo_latitude:
            type: float
            length: 10
            nullable: true
        media_geo_longitude:
            type: float
            length: 10
            nullable: true
        media_date_created:
            type: date
            nullable: true
        media_date_created_end:
            type: date
            nullable: true        
    _indexes:
        date_created_index:
            fields: [item_date_created]      
        item_type_index:
            fields: [item_type]