# src/Zeega/IngestBundle/Resources/config/doctrine/Item.orm.yml
Zeega\IngestBundle\Entity\Item:
    type: entity
    repositoryClass: Zeega\IngestBundle\Repository\ItemRepository
    manyToMany:
        child_items: 
            targetEntity: Item
            inversedBy: parent_items
            joinTable:
                name: Collection
                joinColumns:
                    item_id:
                        referencedColumnName: item_id
                inverseJoinColumns:
                    child_item_id:
                        referencedColumnName: item_id
        parent_items:
            targetEntity: Item
            mappedBy: child_items
    oneToOne:
        metadata:
            targetEntity: Zeega\IngestBundle\Entity\Metadata
            joinColumn:
                name: metadata_id
                referencedColumnName: metadata_id    
        media:
            targetEntity: Zeega\IngestBundle\Entity\Media
            joinColumn:
                name: media_id
                referencedColumnName: media_id    
    id:
        item_id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        item_title:
            type: string
            length: 1000
            nullable: true
        item_creator:
            type: string
            length: 1000
            nullable: false
        item_uri:
            type: string
            length: 200
        item_attribution_uri:
            type: string
            length: 200
        item_date_created:
            type: date
            nullable: false
        item_type:
            type: string
            length: 20
            nullable: false
        item_thumbnail_url:
            type: string
            length: 100
            nullable: true
        item_media_id:
            type: bigint
            nullable: false
        item_metadata_id:
            type: bigint
            nullable: false
        item_child_items_count:
            type: integer
            nullable: true
    _indexes:
        date_created_index:
            fields: [item_date_created]      
        item_type_index:
            fields: [item_type]