# src/Zeega/IngestBundle/Resources/config/doctrine/ItemTags.orm.yml
Zeega\IngestBundle\Entity\ItemTags:
    type: entity
    manyToOne:
        user:
            targetEntity: Zeega\UserBundle\Entity\User
        item:
            targetEntity: Item
            inversedBy: tags
            joinColumn:
                name: item_id
                referencedColumnName: id
        tag:
            targetEntity: Tag
            inversedBy: items
            joinColumn:
                name: tag_id
                referencedColumnName: id
    id:
        item_id:
            type: bigint
        tag_id:
            type: bigint
    fields:
        tag_date_created:
            type: date
            nullable: false