# src/Zeega/IngestBundle/Resources/config/doctrine/Item.orm.yml
Zeega\IngestBundle\Entity\Item:
   type: entity
   repositoryClass: Zeega\IngestBundle\Repository\ItemRepository
   manyToMany:
    items:
     targetEntity: Item
     mappedBy:
      name: parent_collections
    parent_collections:
     targetEntity: Item
     inversedBy:
      name: myParents
     joinTable:
      name: collections
      joinColumns:
       item_id:
        referencedColumnName: id
      inverseJoinColumns:
       child_item_id:
        referencedColumnName: id
   manyToOne:
    playground:
     targetEntity: Zeega\EditorBundle\Entity\Playground
    user:
     targetEntity: Zeega\UserBundle\Entity\User
   oneToOne:
    media:
     targetEntity: Media
     onDelete: CASCADE
    metadata:
     targetEntity: Metadata
     onDelete: CASCADE
   id:
    id:
     type: integer
     generator: { strategy: AUTO }
   fields:
    title:
     type: string
     length: 1000
     nullable: true
    creator:
     type: string
     length: 1000
     nullable: true
    item_url:
     type: string
     length: 200
    attribution_url:
     type: string
     length: 200
    depth:
     type: boolean
     nullable: true
    geo_lat:
     type: float
     length: 10
     nullable: true
    geo_lng: 
     type: float
     length: 10
     nullable: true
    date_created_start:
     type: date
     nullable: true
    date_created_end:
     type: date
     nullable: true
    content_type:
     type: string
     length: 100
    archive:
     type: string
     length: 100
   _indexes:
    geo_index:
     fields: [geo_lat, geo_lng]
    lat_index:
     fields: [geo_lat]
    lng_index: 
     fields: [geo_lng]
    date_start_index:
     fields: [date_created_start]
    date_end_index:
     fields: [date_created_end]
      