# src/Zeega/IngestBundle/Resources/config/doctrine/Metadata.orm.yml
Zeega\IngestBundle\Entity\Metadata:
type: entity
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  description:
   type: string
   length: 5000
   nullable: true
  alt_creator:
   type: string
   length: 100
   nullable: true
  thumb_url:
   type: string
   length: 100
   nullable: true
  license:
   type: string
   length: 50
   nullable: true
  tag_list:
   type: string
   length: 1000
   nullable: true
  attr:
   type: array
   nullable: true
   
  
        