api_projects:
    type: rest
    resource: Zeega\ApiBundle\Controller\ProjectsController
    name_prefix: api_
    prefix:   api    

global_search:
    pattern: /api/search.{_format}
    defaults: { _controller: ZeegaApiBundle:Search:search, _format: json}
    requirements: { _format: (xml|json), _method: GET }

items:
    type:     rest
    prefix:   api
    resource: Zeega\ApiBundle\Controller\ItemsController
    
api_frames:
    type:     rest
    prefix:   api
    resource: Zeega\ApiBundle\Controller\FramesController

api_users:
    type: rest
    prefix: api
    resource: Zeega\ApiBundle\Controller\UsersController
