parameters:
#    zeega_api.example.class: Zeega\ApiBundle\Example

services:
    zeega_api_response_listener:
        class: Zeega\ApiBundle\Listener\ApiResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
