ZeegaBookmarkletBundle_persist:
    pattern: /widget/persist
    defaults: { _controller:  ZeegaBookmarkletBundle:Bookmarklet:persist }

ZeegaBookmarkletBundle_widget:
    pattern: /widget/
    defaults: { _controller:  ZeegaBookmarkletBundle:Bookmarklet:open }
    
