parameters:
#    zeega_extensions.example.class: Zeega\ExtensionsBundle\Example

services:
#    zeega_extensions.example:
#        class: %zeega_extensions.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
