parameters:
#    zeega_social.example.class: Zeega\SocialBundle\Example

services:
    zeega.twitter.user:
        class: Zeega\SocialBundle\Security\User\Provider\TwitterProvider
        arguments:
            twitter_oauth: "@fos_twitter.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            session: "@session"
            logger: "@logger" 
