parameters:
#    zeega_search.example.class: Zeega\SearchBundle\Example

services:
#    zeega_search.example:
#        class: %zeega_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
