parameters:
    zeega_solr.class: Zeega\DataBundle\Service\SolrService

services:
    zeega_solr:
        class: %zeega_solr.class%
        arguments:
            security: "@solarium.client"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }