# src/Zeega/EditorBundle/Resources/config/doctrine/Layer.orm.yml
Zeega\EditorBundle\Entity\Layer:
   type: entity
   repositoryClass: Zeega\EditorBundle\Repository\EditorRepository
   manyToOne:
    item:
     targetEntity: Zeega\IngestBundle\Entity\Item
     joinColumn:
         name: id
         referencedColumnName: item_id         
   id:
    id:
     type: integer
     generator: { strategy: AUTO }
   fields:
    item_uri:
     type: string
     length: 255
     nullable: true
    type:
     type: string
     length: 50
     nullable: true
    text:
     type: string
     length: 1000
     nullable: true
    zindex:
     type: integer
     length: 5
     nullable: true
    attr:
     type: array
     nullable: true
 