# src/Zeega/EditorBundle/Resources/config/doctrine/Playground.orm.yml
Zeega\EditorBundle\Entity\Playground:
   type: entity
   repositoryClass: Zeega\EditorBundle\Repository\EditorRepository
   manyToMany:
    users:
      targetEntity: Zeega\UserBundle\Entity\User
      joinTable:
        name: Users_Playgrounds
        joinColumns:
          playground_id:
            referencedColumnName: id
        inverseJoinColumns:
          user_id:
            referencedColumnName: id
   id:
    id:
     type: integer
     generator: { strategy: AUTO }
   fields:
    title:
     type: string
     length: 255
     nullable: true
    short:
     type: string
     length: 255
     nullable: true
     unique: true
    published:
     type: boolean
     nullable: true
    created_at:
     type: datetime
     nullable: true

 
 