# src/Zeega/EditorBundle/Resources/config/doctrine/Project.orm.yml
Zeega\EditorBundle\Entity\Project:
   type: entity
   repositoryClass: Zeega\EditorBundle\Repository\EditorRepository
   manyToMany:
    users:
     targetEntity: Zeega\UserBundle\Entity\User
     inversedBy:
      name: projects
     joinTable:
      name: project_users
      joinColumns:
       project_id:
        referencedColumnName: id
      inverseJoinColumns:
       user_id:
        referencedColumnName: id
   manyToOne:
    playground:
     targetEntity: Playground
   id:
    id:
     type: integer
     generator: { strategy: AUTO }
   fields:
    title:
     type: string
     length: 255
     nullable: true
    published:
     type: boolean
     nullable: true
    created_at:
     type: datetime
     nullable: true

 