# src/Zeega/IngestBundle/Resources/config/doctrine/ItemTags.orm.yml
Zeega\DataBundle\Entity\ItemTags:
    type: entity
    repositoryClass: Zeega\IngestBundle\Repository\ItemTagsRepository
    manyToOne:
        user:
            targetEntity: Zeega\DataBundle\Entity\User
        item:
            targetEntity: Item
            inversedBy: tags
        tag:
            targetEntity: Tag
            inversedBy: items
    id:
        item:
            associationKey: true
        tag:
            associationKey: true
    fields:
        tag_date_created:
            type: datetime
            nullable: false