# src/Zeega/\CoreBundle\/Resources/config/doctrine/Item.orm.yml
Zeega\DataBundle\Entity\Item:
    type: entity
    repositoryClass: Zeega\DataBundle\Repository\ItemRepository
    lifecycleCallbacks:
       prePersist: [onPrePersist]
    manyToMany:
        child_items: 
            targetEntity: Item
            inversedBy: parent_items
            onDelete: CASCADE
            joinTable:
                name: Collection
                joinColumns:
                    id:
                        referencedColumnName: id
                inverseJoinColumns:
                    child_item_id:
                        referencedColumnName: id
        parent_items:
            targetEntity: Item
            mappedBy: child_items
    oneToOne:
        media:
            targetEntity: Media
            inversedBy: item
            onDelete: CASCADE
            joinColumn:
                name: media_id
                referencedColumnName: id
        metadata:
            targetEntity: Metadata
            inversedBy: item
            onDelete: CASCADE
            joinColumn:
                name: metadata_id
                referencedColumnName: id
    oneToMany:
        tags:
            targetEntity: ItemTags
            mappedBy: item
            joinColumn:
                name: id
                referencedColumnName: item_id
    manyToOne:
        playground:
            targetEntity: Zeega\DataBundle\Entity\Playground
        user:
            targetEntity: Zeega\DataBundle\Entity\User
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        media_id:
            type: bigint
            nullable: true
        metadata_id:
            type: bigint
            nullable: true
        playground_id:
            type: integer
            nullable: true            
        title:
            type: string
            length: 1000
            nullable: true
        user_id:
            type: integer
            nullable: false
        description:
            type: string
            nullable: true
        text:
            type: text
            nullable: true
        uri:
            type: string
            length: 200
        attribution_uri:
            type: string
            length: 200
        date_created:
            type: datetime
            nullable: true
        type:
            type: string
            length: 20
            nullable: false
        source:
            type: string
            length: 20
            nullable: false        
        thumbnail_url:
            type: string
            length: 500
            nullable: true
        child_items_count:
            type: integer
            nullable: false
            default: default 0
        media_geo_latitude:
            type: float
            length: 10
            nullable: true
        media_geo_longitude:
            type: float
            length: 10
            nullable: true
        media_date_created:
            type: datetime
            nullable: true
        media_date_created_end:
            type: datetime
            nullable: true        
        media_creator_username:
            type: string
            length: 80
            nullable: false
        media_creator_realname:
            type: string
            length: 80
            nullable: false
    _indexes:
        date_created_index:
            fields: [item_date_created]      
        item_type_index:
            fields: [item_type]
