# src/Zeega/EditorBundle/Resources/config/doctrine/Layer.orm.yml
Zeega\DataBundle\Entity\Layer:
   type: entity
   repositoryClass: Zeega\DataBundle\Repository\EditorRepository
   manyToOne:
    item:
     targetEntity: Zeega\DataBundle\Entity\Item
   manyToMany:
    sequences:
     targetEntity: Zeega\DataBundle\Entity\Sequence
     mappedBy: layers
   id:
    id:
     type: bigint
     generator: { strategy: AUTO }
   fields:
    item_uri:
     type: string
     length: 255
     nullable: true
    type:
     type: string
     length: 50
     nullable: true
    text:
     type: string
     length: 1000
     nullable: true
    zindex:
     type: integer
     length: 5
     nullable: true
    attr:
     type: array
     nullable: true
 