# src/Zeega/EditorBundle/Resources/config/doctrine/Route.orm.yml
Zeega\DataBundle\Entity\Route:
   type: entity
   repositoryClass: Zeega\DataBundle\Repository\EditorRepository
   manyToOne:
    project:
     targetEntity: Project
     onDelete: CASCADE
     joinColumns:
       project_id:
        referencedColumnName: id
        onDelete: CASCADE
   manyToMany:
    layers:
     targetEntity: Layer
     inversedBy:
      name: routes
     joinTable:
      name: routes_layers
      joinColumns:
       route_id:
        referencedColumnName: id
        onDelete: CASCADE
      inverseJoinColumns:
       layer_id:
        referencedColumnName: id
        onDelete: CASCADE
   id:
    id:
     type: integer
     generator: { strategy: AUTO }
   fields:
    title:
     type: string
     length: 255
    attr:
     type: array
     nullable: true

 