Zeega\DataBundle\Entity\Schedule:
    type: entity
    table: schedule
    manyToOne:
        user:
            targetEntity: Zeega\DataBundle\Entity\User
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        query:
            type: string
            length: 100
            nullable: true
        tags:
            type: string
            length: 100
            nullable: true
        target_service:
            type: string
            length: 25
            nullable: false
        date_created:
            type: datetime
            nullable: false
        date_updated:
            type: datetime
            nullable: false
        status:
            type: string
            length: 10
            nullable: false        
        status_message:
            type: string
            length: 255
            nullable: false
        enabled:
            type: boolean
            nullable: false

    indexes:
        schedule_id:
            columns: [id]
        schedule_status:
            columns: [status]
        schedule_enabled:
            columns: [enabled]