# src/Zeega/UserBundle/Resources/config/doctrine/User.orm.yml
Zeega\DataBundle\Entity\User:
    type: entity
    table: zuser
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToMany:
        sites:
            targetEntity: UsersSites
            mappedBy: user
    fields:
        display_name:
            type: string
            length: 255
            nullable: true
        bio:
            type: text
            nullable: true
        thumb_url:
            type: string
            length: 255
            nullable: true
        created_at:
            type: datetime
            nullable: true
