ZeegaCoreBundle_celery:
  pattern: /celery/queue
  defaults: { _controller: ZeegaCoreBundle:Celery:queue }

sites:
  type:     rest
  resource: Zeega\CoreBundle\Controller\SitesController
  
ZeegaCoreBundle_home:
    pattern: /
    defaults: { _controller:  ZeegaCoreBundle:Editor:home }

ZeegaCoreBundle_site:
    pattern: /site/{short}
    defaults: { _controller:  ZeegaCoreBundle:Editor:site }

ZeegaCoreBundle_editor:
    pattern: /site/{short}/project/{id}
    defaults: { _controller:  ZeegaCoreBundle:Editor:editor }

ZeegaCoreBundle_faq:
    pattern: /faq
    defaults: { _controller:  ZeegaCoreBundle:Core:faq }
    
ZeegaCoreBundle_unsupportedBrowser:
    pattern: /browser/notsupported
    defaults: { _controller:  ZeegaCoreBundle:Core:unsupportedBrowser }

ZeegaCoreBundle_frame_publish:
    pattern: /frame/{id}/view
    defaults: { _controller:  ZeegaCoreBundle:Publish:frame }

ZeegaCoreBundle_project_publish:
    pattern: /project/{id}/view
    defaults: { _controller:  ZeegaCoreBundle:Publish:project }

ZeegaCoreBundle_collection_publish:
    pattern: /collection/{id}/view
    defaults: { _controller:  ZeegaCoreBundle:Publish:collection }
    
ZeegaCoreBundle_embed:
    pattern: /{id}
    defaults: { _controller:  ZeegaCoreBundle:Publish:embed }

    
