projects:
  type:     rest
  resource: Zeega\CoreBundle\Controller\ProjectsController

sequences:
  type:     rest
  resource: Zeega\CoreBundle\Controller\SequencesController

frames:
  type:     rest
  resource: Zeega\CoreBundle\Controller\FramesController

layers:
  type:     rest
  resource: Zeega\CoreBundle\Controller\LayersController

sites:
  type:     rest
  resource: Zeega\CoreBundle\Controller\SitesController
  
ZeegaCoreBundle_home:
    pattern: /
    defaults: { _controller:  ZeegaCoreBundle:Editor:home }

ZeegaCoreBundle_site:
    pattern: /site/{short}
    defaults: { _controller:  ZeegaCoreBundle:Editor:site }
    
ZeegaCoreBundle_admin:
    pattern: /site/{short}/admin
    defaults: { _controller:  ZeegaCoreBundle:Editor:admin }

ZeegaCoreBundle_editor:
    pattern: /site/{short}/project/{id}
    defaults: { _controller:  ZeegaCoreBundle:Editor:editor }
    
ZeegaCoreBundle_browser:
    pattern: /site/{short}/browser
    defaults: { _controller:  ZeegaCoreBundle:Editor:browser }

ZeegaCoreBundle_project:
    pattern: /site/{short}/project
    defaults: { _controller:  ZeegaCoreBundle:Editor:project }
    
ZeegaCoreBundle_faq:
    pattern: /faq
    defaults: { _controller:  ZeegaCoreBundle:Editor:faq }

ZeegaCoreBundle_frame_publish:
    pattern: /frame/{id}/view
    defaults: { _controller:  ZeegaCoreBundle:Publish:frame }

ZeegaCoreBundle_project_publish:
    pattern: /project/{id}/view
    defaults: { _controller:  ZeegaCoreBundle:Publish:project }

ZeegaCoreBundle_collection_publish:
    pattern: /collection/{id}/view
    defaults: { _controller:  ZeegaCoreBundle:Publish:collection }

ZeegaCoreBundle_siteadmin:
    pattern: /siteadmin
    defaults: { _controller:  ZeegaCoreBundle:Editor:siteadmin }

ZeegaCoreBundle_settings:
    pattern: /settings
    defaults: { _controller:  ZeegaCoreBundle:Editor:settings }