parameters:
#    zeega_core.example.class: Zeega\CoreBundle\Example

services:
#    zeega_core.example:
#        class: %zeega_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
